# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Title', kernelModule='dummy_insert', kernelFunction='dummy_inset', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgLabel(p='DialogBox', text='\xb1\xb8\xd7\xa2\xa3\xba\xb2\xe5\xc8\xeb\xb5\xc4\xca\xc7CPE4P\xb5\xa5\xd4\xaa\xa3\xac\xd3\xc3\xc0\xb4\xce\xaa\xd7\xaa\xbb\xbb\xd7\xf6\xd7\xbc\xb1\xb8', useBoldFont=True)
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Part:', keyword='partName', default='', comboType='MDB', repository='parts', rootText='Model:', rootKeyword='modelName', layout='HORIZONTAL')
dialogBox.show()