# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='\xcf\xcb\xce\xac\xb2\xe5\xc8\xeb\xb9\xa4\xbe\xdf', kernelModule='Fibre_insert', kernelFunction='Fibre_insert', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgCheckButton(p='DialogBox', text='uel\xc4\xa3\xca\xbd', keyword='uel_mode', default=False)
RsgTabBook(name='TabBook_1', p='DialogBox', layout='0')
RsgTabItem(name='TabItem_1', p='TabBook_1', text='\xcf\xcb\xce\xac\xb2\xe5\xc8\xeb')
RsgGroupBox(name='GroupBox_1', p='TabItem_1', text='Title', layout='0')
RsgHorizontalFrame(name='HFrame_2', p='GroupBox_1', layout='0', pl=0, pr=0, pt=20, pb=0)
RsgComboBox(name='ComboBox_2', p='GroupBox_1', text='Part:', keyword='partName', default='', comboType='MDB', repository='parts', rootText='Model:', rootKeyword='modelName', layout='HORIZONTAL')
RsgHorizontalFrame(name='HFrame_3', p='GroupBox_1', layout='0', pl=0, pr=0, pt=10, pb=10)
RsgPickButton(p='GroupBox_1', text='\xd1\xa1\xd4\xf1\xb2\xbb\xb2\xe5\xc8\xeb\xb5\xc4\xb1\xdf', keyword='variable', prompt='Pick an entity', entitiesToPick='MDB_GEOMETRY|EDGES', numberToPick='MANY')
RsgHorizontalFrame(name='HFrame_1', p='GroupBox_1', layout='0', pl=0, pr=0, pt=0, pb=20)
RsgTabItem(name='TabItem_2', p='TabBook_1', text='\xb2\xce\xca\xfd\xc9\xe8\xd6\xc3\r\n')
RsgTextField(p='TabItem_2', fieldType='Integer', ncols=12, labelText='\xc6\xbd\xc3\xe6\xcd\xe2\xba\xf1\xb6\xc8:', keyword='thick', default='10')
RsgComboBox(name='ComboBox_4', p='TabItem_2', text='\xca\xd4\xd1\xe9\xb7\xbd\xca\xbd\r\n', keyword='pattern', default='TPB', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_4', text='TPB')
RsgListItem(p='ComboBox_4', text='PULLOUT')
RsgComboBox(name='ComboBox_5', p='TabItem_2', text='\xbb\xec\xc4\xfd\xcd\xc1\xc7\xbf\xb6\xc8:', keyword='strength', default='C50', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_5', text='C15')
RsgListItem(p='ComboBox_5', text='C20')
RsgListItem(p='ComboBox_5', text='C25')
RsgListItem(p='ComboBox_5', text='C30')
RsgListItem(p='ComboBox_5', text='C35')
RsgListItem(p='ComboBox_5', text='C40')
RsgListItem(p='ComboBox_5', text='C45')
RsgListItem(p='ComboBox_5', text='C50')
RsgListItem(p='ComboBox_5', text='C55')
RsgListItem(p='ComboBox_5', text='C60')
RsgListItem(p='ComboBox_5', text='C65')
RsgListItem(p='ComboBox_5', text='C70')
RsgListItem(p='ComboBox_5', text='C75')
RsgListItem(p='ComboBox_5', text='C80')
RsgGroupBox(name='GroupBox_2', p='TabItem_2', text='\xcf\xcb\xce\xac', layout='LAYOUT_FILL_X|LAYOUT_FILL_Y')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=3, labelText='\xb0\xeb\xbe\xb6:', keyword='diameter', default='0.1')
RsgCheckButton(p='GroupBox_2', text='\xbd\xd3\xb4\xa5\r', keyword='interact', default=False)
dialogBox.show()